language: cpp
dist: bionic

matrix:
  include:
  - env: CXX="g++-7" CC="gcc-7"
    os: linux
    addons:
      apt:
        packages: ['g++-7', 'cppcheck']
        sources: ['ubuntu-toolchain-r-test']
    after_success:
      - cppcheck ../src/

  - env: CXX="clang++-6.0" CC="clang-6.0"
    os: linux
    addons:
      apt:
        packages: ['clang-6.0']
        sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-bionic-6.0']

before_install:
  - sudo apt-get -y install libssl-dev libsodium-dev

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export CXX="clang++" CC="clang"; fi
  - $CXX --version
  - cmake --version

script:
    - mkdir -p build && cd build
    - cmake ..
    - make -j2
    - make install
    - (cd ../dist/bin/ && (echo "password" | ./mick generate-keypair --keypair-path=/tmp) && mv /tmp/identity.pk /tmp/test.pk && mv /tmp/identity.sk /tmp/test.sk)
    - make test CTEST_OUTPUT_ON_FAILURE=TRUE
